services:
  db:
    image: postgres:15-alpine
    container_name: minierp_db
    restart: always
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d${DB_NAME}'"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minierp_app
    restart: always
    environment: 
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes : ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    depends_on: 
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  pgdata: